import { useState, useEffect } from "react";
import { fetchLeaveHistory } from "../services/api";

export default function AuditLogs() {
  const [logs, setLogs] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchLeaveHistory()
      .then((res) => setLogs(res.history || []))
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="audit-container">
      <div className="panel-card">
        <div className="panel-header">
          <div>
            <h3>📑 Multi-Agent Governance & Audit Trail</h3>
            <p>Immutable audit trail generated by AuditAgent & stored in SQLite database</p>
          </div>
          <button type="button" className="btn-secondary" onClick={() => fetchLeaveHistory().then((r) => setLogs(r.history || []))}>
            🔄 Refresh Audit Logs
          </button>
        </div>

        <div className="table-responsive">
          <table className="custom-table">
            <thead>
              <tr>
                <th>Workflow ID</th>
                <th>Event Type</th>
                <th>Subject</th>
                <th>Leave Type</th>
                <th>Days</th>
                <th>AI Decision</th>
                <th>Timestamp</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr>
                  <td colSpan="7" className="text-center py-4">Loading audit logs...</td>
                </tr>
              ) : logs.length > 0 ? (
                logs.map((log) => (
                  <tr key={log.workflow_id}>
                    <td><code>{log.workflow_id}</code></td>
                    <td><span className="event-badge">WORKFLOW_PROCESSED</span></td>
                    <td><strong>{log.employee_name}</strong></td>
                    <td>{log.leave_type}</td>
                    <td>{log.days} days</td>
                    <td>
                      <span className={`decision-pill ${log.recommendation === "APPROVED" ? "approved" : "rejected"}`}>
                        {log.recommendation}
                      </span>
                    </td>
                    <td><small>{new Date(log.created_at).toLocaleString()}</small></td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan="7" className="text-center py-4">No audit logs recorded yet.</td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
